"""Fix user_id column type from INTEGER to STRING in task table

Revision ID: 94f8bf6e85ee
Revises: 4aa15c160cad
Create Date: 2026-01-15 19:22:45.085578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f8bf6e85ee'
down_revision: Union[str, Sequence[str], None] = '4aa15c160cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.alter_column('task', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('task', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
